# Generated by Django 5.1.3 on 2025-11-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/fotos/', verbose_name='Foto'),
        ),
    ]
