# Generated by Django 5.2.8 on 2025-11-08 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('Factura', 'Factura'), ('Boleta', 'Boleta')], max_length=7)),
                ('folio', models.IntegerField(verbose_name='Folio')),
                ('neto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Neto')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('estado', models.CharField(choices=[('Emitida', 'Emitida'), ('Pagada', 'Pagada'), ('Vencida', 'Vencida'), ('Anulada', 'Anulada'), ('Pago Parcial', 'Pago Parcial')], default='Emitida', max_length=12)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento')),
                ('medio_de_pago', models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Tarjeta de Débito', 'Tarjeta de Débito'), ('Tarjeta de Crédito', 'Tarjeta de Crédito'), ('Transferencia', 'Transferencia')], max_length=20, null=True, verbose_name='Medio de pago')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('pedido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.pedido', verbose_name='Pedido asociado')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Documento de Venta',
                'verbose_name_plural': 'Documentos de Venta',
                'db_table': 'documentos_venta',
                'ordering': ['-fecha_emision'],
                'unique_together': {('tipo_documento', 'folio')},
            },
        ),
        migrations.CreateModel(
            name='DetalleDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('costo_unitario_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo unitario al momento de la venta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='documentos.documentoventa')),
            ],
            options={
                'verbose_name': 'Detalle de Documento',
                'verbose_name_plural': 'Detalles de Documento',
                'db_table': 'detalle_documento',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pago')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto pagado')),
                ('metodo_pago', models.CharField(max_length=50, verbose_name='Método de pago')),
                ('referencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia/Número de operación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='documentos.documentoventa')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
