# Generated by Django 5.2.7 on 2025-11-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoventa',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Neto'),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total'),
        ),
    ]
