# Generated by Django 5.2.7 on 2025-11-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_documentoventa_ciudad_documentoventa_comuna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoventa',
            name='fecha_emision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha emisión'),
        ),
    ]
