# Generated by Django 5.2.7 on 2025-11-17 15:36

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_alter_documentoventa_fecha_emision'),
        ('productos', '0003_alter_producto_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate)),
                ('motivo', models.TextField()),
                ('monto', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('estado', models.CharField(choices=[('Emitida', 'Emitida'), ('Aplicada', 'Aplicada')], default='Emitida', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito', to='documentos.documentoventa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleNotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio_unitario', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='documentos.notacredito')),
            ],
        ),
    ]
