# Generated by Django 5.2.7 on 2025-11-17 15:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_notacredito_detallenotacredito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallenotacredito',
            options={'verbose_name': 'Detalle Nota de Crédito', 'verbose_name_plural': 'Detalles Nota de Crédito'},
        ),
        migrations.AlterField(
            model_name='detallenotacredito',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallenotacredito',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='documentoventa',
            name='estado',
            field=models.CharField(choices=[('Emitida', 'Emitida'), ('Pagada', 'Pagada'), ('Vencida', 'Vencida'), ('Anulada', 'Anulada'), ('Pago Parcial', 'Pago Parcial'), ('Devuelta', 'Devuelta'), ('Devuelta Parcial', 'Devuelta Parcial')], default='Emitida', max_length=20),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterModelTable(
            name='detallenotacredito',
            table='detalle_nota_credito',
        ),
    ]
